### ISSUE TITLE
The plugin removes the prefix in Maincraft 1.12.2

### ISSUE THREAD

**Issue by Fiks75** [Ridys/RiPrefix#1]
When the player enters the command /rips me [prefix] for the first time, the prefix is not set. He is deleted. Message: "Your prefix has been removed!"
MC 1.12.2.

Если понимаете по-русски, то лучше на русском напишу.
При первом вводе команды /rips me [prefix] префикс не устанавливается, а сразу удаляется и выскакивает сообщение "Your prefix has been removed!" Последующий ввод команды ничего не меняет, префикс все равно удаляется. Происходит на версии 1.12.2.

**Comment by Ridys** [comment]
I just checked the plugin for 1.12.2. The prefixes are set correctly.

- Please tell me which permissions plugin you use and version
- Do you use ColoredTags plugin?
