### ISSUE TITLE
Add permission to the command /rips

### ISSUE THREAD

**Issue by Fiks75** [Ridys/RiPrefix#3]
Thank you. But you can please add permission to the command /rips, so that not all players looked at the help.

`Добавьте пожалуйста разрешение на команду /rips. Не хочется, чтобы игроки, которые не имеют разрешений на смену префикса видели помощь.`

**Comment by Ridys** [comment]
I will add this permission in ver. 2.1.1, but it will be available by default. To take the access to the help page command, write "-riprefix.help" in your permissions file.

> RU: Я добавлю это право в версии 2.1.1, но оно будет активным по умолчанию. Чтобы забрать доступ к команде, которая выводит страницу помощи, пропишите право "-riprefix.help" к нужной группе прав.
